### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by DonJayamanne** [marcpabst/PdfiumLight#7]
Thanks for creating this fabulous package. 
Please could you provide some samples.

**Comment by marcpabst** [comment]
Hi there. Please note that I'm not a professional developer so please be careful with any examples I provide. A year ago I started work on a small pdf viewer I never finished (or touched again), maybe it's of any help to you. (howver I'm don't really know if it still builds)

https://github.com/marcpabst/ElectricPDF
